- name: Configure Servers
  hosts: allnodes
  tasks:
    - name: create etc dir
      become: yes
      file:
        path: /etc/nebula
        state: directory
    - name: create local dir for nebula binary
      file:
        path: ~/nebula
        state: directory
    - name: copy nebula binary
      copy:
        src: ./nebula
        dest: ~/nebula/nebula

    - name: change mode to 755
      shell: sudo chmod 755 ~/nebula/nebula

    - name: copy ca.crt
      become: yes
      copy:
        src: ./ca.crt
        dest: /etc/nebula/ca.crt

- name: configure light house
  hosts: lighthouse
  become: yes
  tasks:
    - name: create ssh key on lighthouse
      shell: |
        cd /etc/nebula
        ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
    - name: copy lighthouse config file
      copy:
        src: ./config-lighthouse.yaml
        dest: /etc/nebula/config.yaml
    - name: copy lighthouse.crt
      copy:
        src: ./lighthouse.crt
        dest: /etc/nebula/host.crt
    - name: copy lighthouse.key
      copy:
        src: ./lighthouse.key
        dest: /etc/nebula/host.key

- name: copy config file to all hosts
  hosts: hosts
  become: yes
  tasks:
    - name: create ssh keys on hosts
      shell: |
        cd nebula/
        ssh-keygen -f ssh_user.key
    - name: copy config.yaml
      copy:
        src: ./config.yaml
        dest: /etc/nebula/config.yaml

  
- name: copy keys and scrt to server-1
  hosts: server-1
  become: yes
  tasks:
    - name: copy server-1.crt
      copy:
        src: ./server-1.crt
        dest: /etc/nebula/host.crt
    - name: copy server-1.key
      copy:
        src: ./server-1.key
        dest: /etc/nebula/host.key

- name: copy keys and scrt to server-2
  hosts: server-2
  become: yes
  tasks:
    - name: copy server-2.crt
      copy:
        src: ./server-2.crt
        dest: /etc/nebula/host.crt
    - name: copy server-2.key
      copy:
        src: ./server-2.key
        dest: /etc/nebula/host.key


#- name: start the service in all servers
#  hosts: all
#  become: yes
#  tasks:
#    - name: run commands
#      shell: |
#        cd ~/nebula/
#        sudo ./nebula -config /etc/nebula/config.yaml
